eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
ms:
  payment-service:
    url: http://PAYMENT-SERVICE/payment/doPayment
